### ISSUE TITLE
Код не работает

### ISSUE THREAD

**Issue by LekasNet** [MasterGroosha/aiogram-3-guide#15]
Не работает код учебника в части про конечные автоматы

ошибки:

ImportError: cannot import name 'Router' from 'aiogram' (/home/runner/Bot-Kursach/venv/lib/python3.8/site-packages/aiogram/__init__.py)

ImportError: cannot import name 'F' from 'aiogram' (/home/runner/Bot-Kursach/venv/lib/python3.8/site-packages/aiogram/__init__.py)

ModuleNotFoundError: No module named 'aiogram.dispatcher.filters.command'

и т д

**Comment by LekasNet** [comment]
> Не работает код учебника в части про конечные автоматы
> 
> ошибки:
> 
> ImportError: cannot import name 'Router' from 'aiogram' (/home/runner/Bot-Kursach/venv/lib/python3.8/site-packages/aiogram/**init**.py)
> 
> ImportError: cannot import name 'F' from 'aiogram' (/home/runner/Bot-Kursach/venv/lib/python3.8/site-packages/aiogram/**init**.py)
> 
> ModuleNotFoundError: No module named 'aiogram.dispatcher.filters.command'
> 
> и т д

**Comment by MasterGroosha** [comment]
Уже неактуально?

**Comment by andreianufr993** [comment]
У меня также. Как в итоге убрать ошибки ?

**Comment by andreianufr993** [comment]
3.0.0b7

Ср, 5 июля 2023 г. в 13:50, Aleksandr ***@***.***>:

**Comment by MasterGroosha** [comment]
@andreianufr993 тогда импорт `from aiogram.filters.command import Command` совершенно правильный.
