### ISSUE TITLE
Некоторые элементы кода несовместимы с версией aiogram 3.0.0b5

### ISSUE THREAD

**Issue by Alpha787** [MasterGroosha/aiogram-3-guide#17]
Приведу примеры из вашего кода и мои исправления для актуальной версии 3.0.0b5:

Ваш [код:](https://mastergroosha.github.io/aiogram-3-guide/quickstart/)
`# Хэндлер на команду `
`@dp.message(commands=["start"])`
`async def cmd_start(message: types.Message):`

Исправление:
`@dp.message(Command(commands=["start"]))`

Дальше везде параметр `commands=["start"]` используем из класса Command.

Дальше [на этой странице](https://mastergroosha.github.io/aiogram-3-guide/messages/) приводится такой код:
`@dp.message(content_types="text")`
`async def echo_with_time(message: types.Message):`

Как я понял в данном случае не обязательно передавать параметры `content_types=` в функцию `message`:
Вместо этого просто используйте `@dp.message()`.
Это пока несколько примеров, которые я нашел

**Comment by MasterGroosha** [comment]
Привет! Код сейчас действительно не адаптирован под более свежие бета-версии aiogram 3.x, о чём есть предупреждение на каждой странице.

По поводу `content_types` замечание неверное. В "тройке" по умолчанию ловятся сообщения любых типов. Правильный вариант будет 

```python
from aiogram import F

@dp.message(F.text)
async def echo_with_time(...)
```

**Comment by Alpha787** [comment]
Я сейчас делаю проект на 3.0.0b5 и стоит ли вообще пользоваться бетой или лучше все_таки ждать релиза?
Возможно ли такое, что какая-то часть кода, которую я использую сейчас не будет работать на релизе?

**Comment by MasterGroosha** [comment]
Есть шансы, что до релиза ещё будут "ломающие" изменения (breaking changes), так что на свой страх и риск.
