### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by DonOutcast** [MasterGroosha/aiogram-3-guide#25]
Привет еще раз, я новенький в вашем ремесле ))
Самый главный вопрос как у меня так и у подавляющего большинства это MVC
Как бы ты разбил обычную скажем команду /start на паттерн MVC?
Что в model ? controller? view?

**Comment by MasterGroosha** [comment]
Привет. У меня встречный вопрос: а зачем тут MVC?  
[Паттерн Handler](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) вполне себе работает с ботами.

**Comment by DonOutcast** [comment]
Можно и без него я согласен с тобой )
Просто я реализовал его на примере Django МVТ в templates храню что будем отображать пользователю
Так как у тебя больше опыта в этом хотел посмотреть на твою реализацию

**Comment by MasterGroosha** [comment]
Идея интересная на первый взгляд, но не пробовал 🤷‍♂️
