### ISSUE TITLE
Нерабочий фильтр в примере.

### ISSUE THREAD

**Issue by globalwa** [MasterGroosha/aiogram-3-guide#28]
Глава "Фильтры и мидлвари", пункт "Примеры мидлварей".

> handlers/checkin.py
```
@router.callback_query(F.text == "confirm")
async def checkin_confirm(callback: CallbackQuery):
    await callback.answer(
        "Спасибо, подтверждено!",
        show_alert=True
    )
```

Заменить `F.text == "confirm"` на `F.data == "confirm"`. Иначе обработчик не срабатывает при нажатии на кнопку.

**Comment by MasterGroosha** [comment]
Исправлено в a9cee1bff47c4ca478e43c0230faa353716dc9db, спасибо!
