### ISSUE TITLE
Передача именнованых аргументов через Dispatcher()

### ISSUE THREAD

**Issue by Shaonis** [MasterGroosha/aiogram-3-guide#30]
См. [Передача доп. параметров](https://github.com/MasterGroosha/aiogram-3-guide/blob/migrate-to-b7/book_src/quickstart.md#%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B0-%D0%B4%D0%BE%D0%BF-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2--idpass-extras-)

Передавать именованные аргументы можно не только в start_polling(...), но также и через экземпляр диспетчера. Так может быть даже лучше, поскольку это более универсальный вариант для разных способов запуска бота (например через вебхуки)

**Comment by MasterGroosha** [comment]
Спасибо!
Исправлено в https://github.com/MasterGroosha/aiogram-3-guide/pull/72
