### ISSUE TITLE
Неправильный импорт.

### ISSUE THREAD

**Issue by globalwa** [MasterGroosha/aiogram-3-guide#31]
https://mastergroosha.github.io/aiogram-3-guide/fsm/#define-states

> keyboards/simple_row.py

Не работает следующий импорт:
```from aiogram.utils.keyboard import ReplyKeyboardMarkup, KeyboardButton```

Работает:
```from aiogram.types import ReplyKeyboardMarkup, KeyboardButton```

**Comment by globalwa** [comment]
https://mastergroosha.github.io/aiogram-3-guide/fsm/#common-commands

> handlers/common.py

Аналогично:

```
from aiogram.dispatcher.filters.command import Command
from aiogram.dispatcher.filters.text import Text
from aiogram.dispatcher.fsm.context import FSMContext
```

и

```
from aiogram.filters.command import Command
from aiogram.filters.text import Text
from aiogram.fsm.context import FSMContext
```

**Comment by MasterGroosha** [comment]
Спасибо! Исправлено в a3d5e89182b163ea93eb9fc9088c151046957a31

Что касается
> Не работает следующий импорт: from aiogram.utils.keyboard import ReplyKeyboardMarkup, KeyboardButton

У меня этот импорт без проблем работает на beta7, но всё равно заменил на `aiogram.types` для консистентности.
