### ISSUE TITLE
invalid link in section about finite state machines

### ISSUE THREAD

**Issue by KonstantinKlepikov** [MasterGroosha/aiogram-3-guide#34]
[https://mastergroosha.github.io/aiogram-3-guide/fsm/](https://mastergroosha.github.io/aiogram-3-guide/fsm/)

![image](https://user-images.githubusercontent.com/20581667/226931077-6de3090d-16db-4471-bdfb-4b2bc06b4932.png)

this [link](https://github.com/aiogram/aiogram/tree/dev-3.x/aiogram/dispatcher/fsm/storage)

**Comment by MasterGroosha** [comment]
Привет! Спасибо, исправил в 35b32d023f609997b8b1d2e91a7af949389940ec
