### ISSUE TITLE
В fsm.md поправить пример кода команды cancel

### ISSUE THREAD

**Issue by Robotvasya** [MasterGroosha/aiogram-3-guide#35]
[https://github.com/MasterGroosha/aiogram-3-guide/blob/master/book_src/fsm.md   line:313](https://github.com/MasterGroosha/aiogram-3-guide/blob/beffa884f8edeba2d08b01cfeb0235dbfbbea9f7/book_src/fsm.md?plain=1#L313)

@router.message(Command(commands=["cancel"]))
@router.message(Text(text="отмена", text_ignore_case=True))

заменить на 

@router.message(Command(commands=["cancel"]))
@router.message(Text(text="отмена", ignore_case=True))

**Comment by MasterGroosha** [comment]
Привет, спасибо!
Исправлено в 576a27adcb60777dd885f00c140b420d98817d4d
