### ISSUE TITLE
Проверить корректность добавления инлайн клавиатуры ".add" для версий >7

### ISSUE THREAD

**Issue by SergyKo** [MasterGroosha/aiogram-3-guide#41]
фрагмент кода
def get_keyboard_fab():
    buttons = [
        types.InlineKeyboardButton(text="-1", callback_data=callback_numbers.new(action="decr")),
        types.InlineKeyboardButton(text="+1", callback_data=callback_numbers.new(action="incr")),
        types.InlineKeyboardButton(text="Подтвердить", callback_data=callback_numbers.new(action="finish"))
    ]
    keyboard = types.InlineKeyboardMarkup(row_width=2)
    **keyboard.add(*buttons)**
    return keyboard
    
    ссылка на статью https://mastergroosha.github.io/aiogram-2-guide/buttons/#callback-factory

**Comment by MasterGroosha** [comment]
Так ссылка же на гайд по aiogram 2.x

Правильно будет https://mastergroosha.github.io/aiogram-3-guide/buttons/#callback-factory
