### ISSUE TITLE
Колбэки не работают

### ISSUE THREAD

**Issue by jaaguaar** [MasterGroosha/aiogram-3-guide#42]
Здравствуйте,
При попытке повторить материал "книги" столкнулся с тем, что кнопки с callback_data после нажатия ничего не делают :(
Проверка своего кода не привела к результату, поэтому скачал Ваш. Но проблема не пропала, все работает корректно, кроме callback_data. В логе никаких ошибок нет :(
Подскажите пожалуйста, это я что то делаю не так или причина в чем то другом?

**Comment by MasterGroosha** [comment]
А что показывает результат вызова метода getWebhookInfo? Его можно вызвать даже в браузере и даже если поллинг

https://api.telegram.org/botЗДЕСЬТОКЕН/getWebhookInfo

**Comment by jaaguaar** [comment]
Вот такое:
`{"ok":true,"result":{"url":"","has_custom_certificate":false,"pending_update_count":2,"allowed_updates":["message"]}}`

**Comment by jaaguaar** [comment]
Спасибо большое!
