### ISSUE TITLE
Обновить версию aiogram в quickstart.md

### ISSUE THREAD

**Issue by Be3y4uu-K0T** [MasterGroosha/aiogram-3-guide#66]
https://github.com/MasterGroosha/aiogram-3-guide/blob/440cdadc4953ec67877b55cec43c480ac36e003a/book_src/quickstart.md?plain=1#L9
https://github.com/MasterGroosha/aiogram-3-guide/blob/440cdadc4953ec67877b55cec43c480ac36e003a/book_src/quickstart.md?plain=1#L71

Сейчас используется версия 3.0.0rc1 вместо 3.0.0b7. Но в то же время уже вышла версия 3.0.0rc2. 🤓

**Comment by MasterGroosha** [comment]
Да уже и релиз был, надо поправить текст, да

**Comment by Be3y4uu-K0T** [comment]
Done! [77a9049](https://github.com/MasterGroosha/aiogram-3-guide/commit/e4c9b0b7d1b9f45e3f270c05f072d19b477a9049)

P.S.: Ещё бы хотелось прикрутить позже это всё к Python 3.12 (expected: final: Monday, 2023-10-02)

**Comment by MasterGroosha** [comment]
А что с Python 3.12?

**Comment by Be3y4uu-K0T** [comment]
Использовать последнюю версию Python, чтобы туториал был актуален долгое время. А также использовать все новые возможности (конкретно: [PEP 701](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep701), [PEP 692](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep692)[PEP 695](https://docs.python.org/3.12/whatsnew/3.12.html#whatsnew312-pep695))

**Comment by MasterGroosha** [comment]
@Be3y4uu-K0T не вижу в этом смысла по двум основным причинам:

1. После релиза 3.12 я бы подождал как минимум одного патч релиза (3.12.1)
2. Если не целиться специально в фичи 3.12, то код будет работать на 3.9+. Если использовать то, что в 3.12, то мы отсекаем большинство пользователей. Не надо так.

У меня настроен интепретатор на 3.11 в коде из гайда, но я уверен, что всё это будет и на 3.9 работать, а значит, большинство читателей смогут без проблем запустить.

Так что нет, специально тащить фичи 3.12 сюда я не буду.
