### ISSUE TITLE
Pydantic class Config is deprecated

### ISSUE THREAD

**Issue by Be3y4uu-K0T** [MasterGroosha/aiogram-3-guide#67]
aiogram использует pydantic>=2.1.1,<3; в документации pydantic сказано, что class Config устарел:
`Before v2.0, the Config class was used. This is still supported, but deprecated.` [[docs]](https://docs.pydantic.dev/latest/usage/model_config/)

https://github.com/MasterGroosha/aiogram-3-guide/blob/9919c10e34d1cd3c3d12825cc2b1b1e807a3ff40/book_src/quickstart.md?plain=1#L273-L278

Надо использовать: [[docs]](https://docs.pydantic.dev/latest/usage/pydantic_settings/#dotenv-env-support)
```py
from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import SecretStr

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file='.env', env_file_encoding='utf-8')

    bot_token: SecretStr
```

**Comment by MasterGroosha** [comment]
Упс, проглядел, исправлю

**Comment by MasterGroosha** [comment]
Исправлено в 1a67d735c054164f0547373f47b693fe3062ec3e
