### ISSUE TITLE
Ошибка в тексте

### ISSUE THREAD

**Issue by Kymymaru** [MasterGroosha/aiogram-3-guide#71]
кек 
![image](https://github.com/MasterGroosha/aiogram-3-guide/assets/112933427/bbc331ed-940f-4e6f-a54f-ab888646f8a3)
Выше должен просить заголовок, а он 2 раза просит описание.

**Comment by MasterGroosha** [comment]
Спасибо!
Исправлено в https://github.com/MasterGroosha/aiogram-3-guide/pull/72
