### ISSUE TITLE
Передача bot как аргумента функции 

### ISSUE THREAD

**Issue by N1ntek** [MasterGroosha/aiogram-3-guide#76]
В разделе "Особые апдейты" https://mastergroosha.github.io/aiogram-3-guide/special-updates/ , в блоке "Добавление в группу"
в функции "bot_added_as_member" отсутствует аргумент bot, который потом вызывается в ней же.

**Comment by Vadim-Khristenko** [comment]
Привет!
Я не Груша, но решил быстро создать исправление.
Так вот смотри ты можешь использовать.
`await event.bot.get_chat(event.chat.id)`

**Comment by N1ntek** [comment]
> Привет! Я не Груша, но решил быстро создать исправление. Так вот смотри ты можешь использовать. `await event.bot.get_chat(event.chat.id)`
Это понятно) этот issue, чтоб в книжке исправили)

**Comment by MasterGroosha** [comment]
Спасибо, я это притащил в ef4f169 в рамках обновления материалов
