### ISSUE TITLE
Ссылка ведет на некорректный адрес

### ISSUE THREAD

**Issue by stavrmoris** [MasterGroosha/aiogram-3-guide#79]
Ссылка "[Для aiogram 3.x эта глава расположена здесь](https://mastergroosha.github.io/aiogram-3-guide/inline_mode/)" со страницы https://mastergroosha.github.io/aiogram-2-guide/inline_mode/ гайда инлайн режима по aiogram 2 ведет на некорректную страницу.

Ошибка в том что в 3 версии inline-mode пишется через нижнее тире, а во 2 inline_mode через нижнее подчеркивание.

https://github.com/MasterGroosha/aiogram-3-guide/assets/110993331/b3919273-52e9-4e35-b56b-6477d459d5e7

**Comment by MasterGroosha** [comment]
Не надо копировать один и тот же issue в разные репозитории, пожалуйста.
Исправлено в https://github.com/MasterGroosha/aiogram-2-guide/commit/91aa772fe7015298ef923c09559bbda527596a64
