### ISSUE TITLE
Пишем Telegram-ботов с aiogram 3.x, глава  - Знакомство с aiogram.

### ISSUE THREAD

**Issue by nikolay-may** [MasterGroosha/aiogram-3-guide#85]
Добрый день !
Код из файла config_reader.py  может выдавать ошибку -   
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
bot_token
  Field required [type=missing, input_value={}, input_type=dict]

чтобы все работало  нужно дописать в файл  config_reader.py следующие строки 
from dotenv import load_dotenv

load_dotenv()

**Comment by MasterGroosha** [comment]
Это необязательно. Вы файл `.env` создали в каталоге?
