### ISSUE TITLE
Проблема с роутерами

### ISSUE THREAD

**Issue by MasterGroosha** [MasterGroosha/aiogram-3-guide#92]
@MasterGroosha Мастер Груша, прости за очередное беспокойство! Я просто не понимаю, что не так в моем коде. Бот полностью игнорирует все сообщения. 
https://github.com/Dev-Cored/life-author-telegram-bot Вот ссылка на реп. Пытался повторить структуру файлов как в главе с роутерами, но просто нет реакции на сообщения. Просто пишет про игнорирование команды...

_Originally posted by @Dev-Cored in https://github.com/MasterGroosha/aiogram-3-guide/issues/91#issuecomment-2228455598_

**Comment by MasterGroosha** [comment]
Причина простая: в коде сначала стартует поллинг, а уже затем цепляются хэндлеры. А должно быть наоборот, иначе бот стартует без подключенных обработчиков.
https://github.com/Dev-Cored/life-author-telegram-bot/blob/main/bot.py#L23C1-L24C40

Решение: поменять выделенные строки местами.

**Comment by Dev-Cored** [comment]
Огромное спасибо!) Никогда бы не подумал на такую тупую ошибку!
